### ISSUE TITLE
:SortImport does not show error from import-sort

### ISSUE THREAD

**Issue by Ploppz** [ruanyl/vim-sort-imports#4]
I installed import-sort via npm as described in README.md.
When I call `:SortImport` in a .js file, it has no effect. Nothing changes in the file.

**Comment by ruanyl** [comment]
Please try to run import-sort cli and see if there were any error outputs. I cannot help you with the information you provided above.

**Comment by Ploppz** [comment]
CLI seems to work fine
```
$ import-sort
Usage: import-sort [OPTION]... [FILE/GLOB]...

Options:
  --list-different, -l  Print the names of files that are not sorted.  [boolean]
  --write               Edit files in-place.                           [boolean]
  --with-node-modules   Process files inside 'node_modules' directory..[boolean]
  --version, -v         Show version number                            [boolean]
  --help, -h            Show help                                      [boolean]
```

How can I get more information? Can I enable or find logs somehow?

**Comment by ruanyl** [comment]
@Ploppz try to run it with an input file like this:
```
import-sort ./src/test.js
```

**Comment by Ploppz** [comment]
Thanks. Yes, that resulted in an error. I'll post an issue in `import-sort`.
Maybe it would be nice if `vim-sort-imports` could show the error to the user.
